project:
  type: website
  output-dir: docs
  preview:
    port: 7777

website:
  title: "\u03C8ML"
  navbar:
    right:
      - about.qmd
      - header/refs.qmd
      - header/nvim.qmd
      - icon: github
        href: https://github.com/spstolar
format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css



