---
title: Getting Quarto Running from WSL
date: 2024-02-17
---

# Install Quarto

`wget` on the download link for Ubuntu [here](https://quarto.org/docs/get-started/).

Then we have these general steps for installing:

1. Navigate to the Directory Containing the `.deb` File: Use the cd command to change to the directory where your .deb file is located. If the file is in a Windows directory, you can access it from WSL by navigating to /mnt/c (if the file is on the C: drive) followed by the path to the file's location.
2. Install the .deb Package: Once you are in the directory with the .deb file, you can install the package using the dpkg command. If the file name is example.deb, you would use the following command:

```bash
sudo dpkg -i example.deb
```

> The sudo command is used to execute the command with superuser privileges, which are usually required for installing packages. The -i option tells dpkg to install the package.

3. Resolve Dependencies: If the package installation reports missing dependencies, you can attempt to automatically fix this by running:

```bash
sudo apt-get install -f
```

> This command tells APT (the Advanced Package Tool) to fix broken dependencies by downloading and installing any missing packages.

4. Verify Installation: After the installation process completes, you can verify the installation by checking the version of the installed package or by running the application. The specific command for verification will depend on the package you installed.

## Quarto Preview

When you use `quarto preview` you can manually go to `localhost:7777` to see the result or click the link that shows up in the terminal. By default, you'll run into an issue where `xdg-open` does not understand how to open your browser to automate this.

There is one way to get around this by setting up a launch script, but I haven't tried it.

Another way to enable opening a chrome browser from WSL is to follow [this guide](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) for GUI apps via WSL2. This gives you a somewhat janky browser window but this might be preferred if you don't want your chrome details attached to the testing process.

